---
- hosts: webservers
  become: yes
  tasks:
  - name: install jdk8 on ubnutu20 node1
    apt:
      name: "{{myjavaonubuntu}}"
      state: present
    when: ansible_os_family == "Debian"

  - name: install jdk8 on amazonlinux2 node2
    apt:
      name: "{{myjavaonamazonos}}"
      state: present
    when: ansible_os_family == "RedHat"      